### ISSUE TITLE
Filter is not supported

### ISSUE THREAD

**Issue by vakavaka** [generals-space/bootstrap-table-addrbar#1]
The library does not support filtering

**Comment by generals-space** [comment]
I'm sorry that API on my server was down, and do you main the "search" function?

If you do, I would say that the search function should be implement on our server side, this plugin's plugin just put the search text in our request. We need to filter the data with the text and give the response in our backend.

![](https://gitee.com/generals-space/gitimg/raw/master/4a5dc4c411c14221d7b9e208ea23050e.png)

Did you see that?

...Oh, the response in picture still doesn't support "search", because my poor server api do nothing. 

Here is my server code, hope it can help you.

```js
/*
 * 参考: [Node.js:使用hook+shell+git进行自动化构建](https://smallpath.me/post/Node.js:%E4%BD%BF%E7%94%A8git%E5%92%8Cwebhook%E8%BF%9B%E8%A1%8C%E8%87%AA%E5%8A%A8%E5%8C%96%E6%9E%84%E5%BB%BA)
 * */
var express = require('express');
var bodyParser = require('body-parser');

var app = express();
// 挂载中间件, 解析请求中的json数据
// git oschina发来的应该是json格式数据
app.use(bodyParser.json());
// for parsing application/x-www-form-urlencoded
// app.use(bodyParser.urlencoded({ extended: true }));

app.all('/bootstrap-table-addrbar', function(req, res, next){
    // 允许跨域请求
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "X-Requested-With, Content-Type, Origin");
    res.header("Access-Control-Allow-Methods","PUT,POST,GET,DELETE,OPTIONS");
    res.header("Content-Type", "application/json;charset=utf-8");
    if (req.method == 'OPTIONS') {
        res.status(200).send('{"test": "options ok"}');
        return;
    }
    next();
app.all('/bootstrap-table-addrbar', function(req, res, next){
});

var data = function(){
    var _data = [];
    for(var i = 0; i < 100; i ++){
        _data.push({
            id: i,
            name: 'name ' + i,
            price: '$' + i
        });
    }
    return _data;
}();

app.get('/bootstrap-table-addrbar', function(req, res, next){
    console.log(req.query);
    var limit = req.query.limit || 20;
    var offset = req.query.offset || 0;
    var sort = req.query.sort || 'id';
    var order = req.query.order || 'asc';
    var search = req.query.search || '';
    limit = parseInt(limit);
    offset = parseInt(offset);

    var result = {rows: [], total: 100};
    for(var i = 0; i < limit; i ++){
    result.rows.push(data[offset + i]);
    }

    res.json(result);
});

var server = app.listen(3000, function(){
    var host = server.address().address;
    var port = server.address().port;
    console.log('Webhook handler started at http://%s:%s...', host, port);
});
```

**Comment by vakavaka** [comment]
Hey! 
No, the problem is not in server-side. I investigated the issue and now I see that it is not a problem of your library. The problem is that your library is not supporting filters from this lib https://bootstrap-table.com/docs/extensions/filter-control/
This library adds filters on columns, it is a very useful and common task. But these filters are not supported by your lib. I tried to change this behaviour and adapt your lib to these filters but I failed to implement this in a small amount of time, it needs some time to investigate how filter-control lib works and where it stores filters.
You can close this task as this is not a bug from your side. If you want you can improve your lib and add support for filters from filter-control lib, it would be awesome! I think these 2 libs are frequently used together.

**Comment by vakavaka** [comment]
PS: Thanks for fast reply :)
