### ISSUE TITLE
_updateHistoryState called 2x

### ISSUE THREAD

**Issue by N0tMy4cc0unt** [generals-space/bootstrap-table-addrbar#2]
Hello frend,

I hope this issue will find You well.
For a while I was struggling with history states in my implementation of bootstrap-table and this extension. History states are recorded twice, I narrowed to onLoadSuccess and onPageChange events which both are called for page change.

Is my finding OK, or it's something else?

```
$.BootstrapTable = class extends $.BootstrapTable {
  init (...args) {
    if (
      this.options.pagination &&
      this.options.addrbar
    ) {
      // 标志位, 初始加载后关闭
      this.addrbarInit = true

      this.options.pageNumber = +this.getDefaultOptionValue('pageNumber', 'page')
      this.options.pageSize = +this.getDefaultOptionValue('pageSize', 'size')
      this.options.sortOrder = this.getDefaultOptionValue('sortOrder', 'order')
      this.options.sortName = this.getDefaultOptionValue('sortName', 'sort')
      this.options.searchText = this.getDefaultOptionValue('searchText', 'search')

      const _prefix = this.options.addrPrefix || ''
      const _onLoadSuccess = this.options.onLoadSuccess
      const _onPageChange = this.options.onPageChange

      this.options.onLoadSuccess = data => {
        if (this.addrbarInit) {
          this.addrbarInit = false
        } else {
          console.log('this.options.onLoadSuccess');
          _updateHistoryState(this, _prefix) //<-- HERE
        }

        if (_onLoadSuccess) {
          _onLoadSuccess.call(this, data)
        }
      }
      this.options.onPageChange = (number, size) => {
        console.log('this.options.onPageChange');
        _updateHistoryState(this, _prefix)  //<-- HERE

        if (_onPageChange) {
          _onPageChange.call(this, number, size)
        }
      }
    }
    super.init(...args)
  }
```

**Comment by generals-space** [comment]
Yes, I think so.

Actually, i haven't update this repository for a long time after the pr to bootstrap-table. And there is no "onPageChange" function in my code, it could be the bt's author himself added. 

emmm...I think it's a good idea that back/forward button to trigger content changing, I'll add it later.

Maybe you can use "addrbarInit" as a flag to judge when to call "_updateHistoryState"?

**Comment by N0tMy4cc0unt** [comment]
Back/Forward support is more difficult than I anticipated. At the moment I got it working altrough in a very early stage. I commented out both `_updateHistoryState(this, _prefix)` lines in this file and in my code I added on event `onPageChange` lines:
```
        onPageChange: function ($number, $size) {
            let $object = {
                number: $number, 
                size: $size
            };
            window.history.pushState(
                $object, 
                '',
                window.location.href, 
            );
        }
```
With above, in browser history I get point for each table change (except initial load, but I will get back to it later).

To triger table change, I added this `popstate` windovs event listener:

```
window.addEventListener('popstate', function(popstateEvent) {
    //disable BT event onPageChange to avoid browser history update 
    //$('.tableMain').off('page-change.bs.table'); //<--this didnt work
    $('.tableMain').bootstrapTable('refreshOptions',{onPostBody: function() { return undefined; }, onPageChange: function() { return undefined; }});

    //select BT page 
    $('.tableMain').bootstrapTable('selectPage', popstateEvent.state.number);
});

    //refreshOptions on BT
    $('.tableMain').bootstrapTable('refreshOptions', {onPostBody: ......
});
```

Now BT page is changed and refreshed with browser Back/Forward button. But it does not feels like proper solution...

Looking back I see that `_updateHistoryState` have line `window.history.pushState(params, '', _buildUrl(params));` which should put all relevant page parameters in history state. But I got extremely confused when events/triggers start to kickin.. Browser history navigation becomes erratic, partially because BT push new history state on browser back button...

I forgot to mention I'm by no mean skilled FE developer, JS even less, so I'm far from fixing code by myself, but I can contribute with some testing effort...

UPDATE: Now, when click on browser Back, I'm getting 4x OnPostBody event fired:

- 2x for rows of page I'm leaving
- 2x for rows of page I'm arriving

UPDATE2: It's fired 4x on both Back&Forward browser buttons

UPDATE3: I got back to this issue after I had to switch to work on something unrelated. I recall I changed `$('.tableMain').bootstrapTable('refreshOptions', {onPostBody: ......` from `refreshOptions` to `refresh` and now it does not fire 4x. However, while using Back/Forward browser buttons, after each click table is visually repainted two times after 'Loading...' is shown: first with data from previous page then with new page data. Any clue what coud be the cause?

**Comment by generals-space** [comment]
I watched the newest document of bootstrapTable, and found that "onPageChange" is fired before "onLoadSuccess", but I don't recognize the necessary of onPageChange...or can you tell me why😂?

I update my code to implement the Back/Forward function, maybe it can help you. But I think we must modify the addrbar extension's source code...

```js
var _bootstrapTable = $.fn.bootstrapTable;
$.fn.bootstrapTable = function(option){

    _buildParam(_bootstrapTable, option);
    option._onLoadSuccess = option.onLoadSuccess;
    option.onLoadSuccess = function(data){
        // ...
        // h5提供的修改浏览器地址栏的方法
        window.history.pushState({}, '', _buildUrl(params));

        if(option._onLoadSuccess) option._onLoadSuccess.call(this, data);
    };

    var _window = this;
    window.addEventListener('popstate', function(){
        // console.log(this);
        // console.log(_window);
        _buildParam(_bootstrapTable, option);
        _bootstrapTable.call(_window, 'refreshOptions', option);
    });

    return _bootstrapTable.call(this, option);
};
```

Does this work for you?
